/**
 * Bundles the database schema for a real Supabase project.
 *
 *   npm run supabase:sql             → supabase/remote/setup.sql       (schema only)
 *   npm run supabase:sql -- --seed   → supabase/remote/setup+seed.sql  (schema + reference data)
 *
 * The generated file contains, in order:
 *   1. every migration in `supabase/migrations` (tables, constraints, triggers,
 *      RLS policies, storage buckets) inside one transaction,
 *   2. optionally `supabase/seed.sql` (crop catalogue, categories, no prices).
 *
 * Paste it into the Supabase dashboard → SQL Editor → Run. Nothing else is
 * needed to bring a fresh project in line with this repository; the local-only
 * auth shim is deliberately NOT included, because Supabase provides `auth` and
 * `storage` itself.
 */
import "./env";

import fs from "node:fs/promises";
import path from "node:path";

const root = process.cwd();
const migrationsDir = path.join(root, "supabase", "migrations");
const outDir = path.join(root, "supabase", "remote");
const withSeed = process.argv.includes("--seed");

function header(title: string, files: string[]) {
  return [
    "-- ============================================================================",
    `-- X-FARM AI · ${title}`,
    "-- ----------------------------------------------------------------------------",
    "-- Generated by `npm run supabase:sql`. Do not edit by hand: regenerate it.",
    "--",
    "-- How to apply:",
    "--   1. Open your Supabase project → SQL Editor → New query.",
    "--   2. Paste this whole file and press Run.",
    "--   3. Verify with `npm run test:supabase` (from a machine with internet",
    "--      access) — it checks the tables, the RLS policies and the buckets.",
    "--",
    "-- Files included, in order:",
    ...files.map((file, index) => `--   ${String(index + 1).padStart(2, "0")}. ${file}`),
    "-- ============================================================================",
    "",
  ].join("\n");
}

/** Paste into the SQL editor after `setup+seed.sql` for a one-screen report. */
const VERIFY_SQL = `-- X-FARM AI · verification report
-- Run this in Supabase → SQL Editor after setup+seed.sql. It only reads.

with expected_tables as (
  select unnest(array[
    'profiles', 'farms', 'crops', 'soil_records', 'crop_records', 'crop_analyses',
    'weather_records', 'categories', 'listings', 'listing_images', 'machinery',
    'favorites', 'conversations', 'messages', 'notifications', 'reports',
    'market_prices', 'market_price_imports', 'ai_conversations', 'ai_messages',
    'audit_logs', 'usage_events'
  ]) as name
),
missing_tables as (
  select count(*) as missing
  from expected_tables e
  where not exists (
    select 1 from pg_tables t where t.schemaname = 'public' and t.tablename = e.name
  )
),
stats as (
  select
    (select count(*) from pg_tables where schemaname = 'public') as public_tables,
    (select count(*) from pg_tables
       where schemaname = 'public'
         and not rowsecurity
         and tablename <> 'x_farm_migrations') as tables_without_rls,
    (select count(*) from pg_policies where schemaname = 'public') as policies,
    (select count(*) from pg_policies where schemaname = 'public' and qual = 'true') as policies_using_true,
    (select count(*) from storage.buckets
       where id in ('avatars', 'listing-images', 'crop-images')) as storage_buckets,
    (select count(*) from public.crops) as crops,
    (select count(*) from public.categories) as categories,
    (select count(*) from public.market_prices) as market_prices
)
select
  s.public_tables,
  m.missing as expected_tables_missing,
  s.tables_without_rls,
  s.policies,
  s.policies_using_true,
  s.storage_buckets,
  s.crops,
  s.categories,
  s.market_prices,
  case
    when m.missing = 0
     and s.tables_without_rls = 0
     and s.policies >= 57
     and s.policies_using_true = 0
     and s.storage_buckets = 3
     and s.crops > 0
     and s.categories > 0
    then 'OK — schema, RLS, buckets and reference data are in place'
    when m.missing > 0
    then 'FAILED — expected_tables_missing > 0: the setup did not finish, run setup+seed.sql again'
    else 'CHECK — read the numbers above against section 6.5 of README.md'
  end as verdict
from stats s, missing_tables m;
`;

async function main() {
  const entries = (await fs.readdir(migrationsDir)).filter((file) => file.endsWith(".sql")).sort();
  if (entries.length === 0) throw new Error("No migration files found in supabase/migrations.");

  const files = entries.map((file) => `supabase/migrations/${file}`);
  const parts: string[] = [];

  parts.push(header(withSeed ? "Supabase setup + reference data" : "Supabase setup", files));
  parts.push("begin;");
  parts.push("");

  for (const file of entries) {
    const relative = `supabase/migrations/${file}`;
    const sql = await fs.readFile(path.join(migrationsDir, file), "utf8");
    parts.push("-- ----------------------------------------------------------------------------");
    parts.push(`-- ${relative}`);
    parts.push("-- ----------------------------------------------------------------------------");
    parts.push(sql.trim());
    parts.push("");
  }

  if (withSeed) {
    const seedSql = await fs.readFile(path.join(root, "supabase", "seed.sql"), "utf8");
    parts.push("-- ----------------------------------------------------------------------------");
    parts.push("-- supabase/seed.sql  (reference data: crop catalogue + categories, no prices)");
    parts.push("-- ----------------------------------------------------------------------------");
    parts.push(seedSql.trim());
    parts.push("");
  }

  parts.push("commit;");
  parts.push("");

  await fs.mkdir(outDir, { recursive: true });
  const outFile = path.join(outDir, withSeed ? "setup+seed.sql" : "setup.sql");
  await fs.writeFile(outFile, parts.join("\n"), "utf8");

  // A small companion query so "did it work?" is answerable inside the SQL
  // editor as well, without waiting for `npm run test:supabase`.
  const verifyFile = path.join(outDir, "verify.sql");
  await fs.writeFile(verifyFile, VERIFY_SQL, "utf8");

  const relative = path.relative(root, outFile);
  console.log(`Wrote ${relative}`);
  console.log(`  migrations: ${entries.length}`);
  console.log(`  seed data : ${withSeed ? "included" : "not included (add --seed)"}`);
  console.log(`Wrote ${path.relative(root, verifyFile)}`);
  console.log("\nPaste that file into Supabase → SQL Editor → Run, then check the project with:");
  console.log("  npm run test:supabase");
}

main().catch((error) => {
  console.error("[supabase:sql] failed:", error instanceof Error ? error.message : error);
  process.exitCode = 1;
});
