/**
 * Bundles the database schema for a real Supabase project.
 *
 *   npm run supabase:sql             → supabase/remote/setup.sql       (schema only)
 *   npm run supabase:sql -- --seed   → supabase/remote/setup+seed.sql  (schema + reference data)
 *
 * The generated file contains, in order:
 *   1. every migration in `supabase/migrations` (tables, constraints, triggers,
 *      RLS policies, storage buckets) inside one transaction,
 *   2. optionally `supabase/seed.sql` (crop catalogue, categories, no prices).
 *
 * Paste it into the Supabase dashboard → SQL Editor → Run. Nothing else is
 * needed to bring a fresh project in line with this repository; the local-only
 * auth shim is deliberately NOT included, because Supabase provides `auth` and
 * `storage` itself.
 */
import "./env";

import fs from "node:fs/promises";
import path from "node:path";

const root = process.cwd();
const migrationsDir = path.join(root, "supabase", "migrations");
const outDir = path.join(root, "supabase", "remote");
const withSeed = process.argv.includes("--seed");

function header(title: string, files: string[]) {
  return [
    "-- ============================================================================",
    `-- X-FARM AI · ${title}`,
    "-- ----------------------------------------------------------------------------",
    "-- Generated by `npm run supabase:sql`. Do not edit by hand: regenerate it.",
    "--",
    "-- How to apply:",
    "--   1. Open your Supabase project → SQL Editor → New query.",
    "--   2. Paste this whole file and press Run.",
    "--   3. Verify with `npm run test:supabase` (from a machine with internet",
    "--      access) — it checks the tables, the RLS policies and the buckets.",
    "--",
    "-- Files included, in order:",
    ...files.map((file, index) => `--   ${String(index + 1).padStart(2, "0")}. ${file}`),
    "-- ============================================================================",
    "",
  ].join("\n");
}

async function main() {
  const entries = (await fs.readdir(migrationsDir)).filter((file) => file.endsWith(".sql")).sort();
  if (entries.length === 0) throw new Error("No migration files found in supabase/migrations.");

  const files = entries.map((file) => `supabase/migrations/${file}`);
  const parts: string[] = [];

  parts.push(header(withSeed ? "Supabase setup + reference data" : "Supabase setup", files));
  parts.push("begin;");
  parts.push("");

  for (const file of entries) {
    const relative = `supabase/migrations/${file}`;
    const sql = await fs.readFile(path.join(migrationsDir, file), "utf8");
    parts.push("-- ----------------------------------------------------------------------------");
    parts.push(`-- ${relative}`);
    parts.push("-- ----------------------------------------------------------------------------");
    parts.push(sql.trim());
    parts.push("");
  }

  if (withSeed) {
    const seedSql = await fs.readFile(path.join(root, "supabase", "seed.sql"), "utf8");
    parts.push("-- ----------------------------------------------------------------------------");
    parts.push("-- supabase/seed.sql  (reference data: crop catalogue + categories, no prices)");
    parts.push("-- ----------------------------------------------------------------------------");
    parts.push(seedSql.trim());
    parts.push("");
  }

  parts.push("commit;");
  parts.push("");

  await fs.mkdir(outDir, { recursive: true });
  const outFile = path.join(outDir, withSeed ? "setup+seed.sql" : "setup.sql");
  await fs.writeFile(outFile, parts.join("\n"), "utf8");

  const relative = path.relative(root, outFile);
  console.log(`Wrote ${relative}`);
  console.log(`  migrations: ${entries.length}`);
  console.log(`  seed data : ${withSeed ? "included" : "not included (add --seed)"}`);
  console.log("\nPaste that file into Supabase → SQL Editor → Run, then check the project with:");
  console.log("  npm run test:supabase");
}

main().catch((error) => {
  console.error("[supabase:sql] failed:", error instanceof Error ? error.message : error);
  process.exitCode = 1;
});
